# Generated by Django 5.0.6 on 2026-05-19 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_sellerdiscount_selleractivity_returnrequest_seller_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selleractivity",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="sellerdiscount",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
