# Generated by Django 6.0.5 on 2026-05-10 04:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=256)),
                ('address_line', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_seller',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerOrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Seller Action'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=15)),
                ('delivery_partner', models.CharField(blank=True, choices=[('bluedart', 'Blue Dart Express'), ('delhivery', 'Delhivery'), ('dtdc', 'DTDC Courier'), ('ecom', 'Ecom Express'), ('xpressbees', 'XpressBees'), ('shadowfax', 'Shadowfax')], max_length=20, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller_orderrequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
