# Generated by Django 6.0.5 on 2026-05-10 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorderrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_requests', to='store.order'),
        ),
        migrations.AddField(
            model_name='sellerorderrequest',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_request', to='store.orderitem'),
        ),
        migrations.AddField(
            model_name='sellerorderrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='seller.seller'),
        ),
    ]
