# Generated by Django 5.0.6 on 2026-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_pendingquestion_seller_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[("answered", "Answered"), ("pending", "Pending")],
                default="answered",
                max_length=20,
            ),
        ),
    ]
